// Generated by gencpp from file sensor/radius_msgs.msg
// DO NOT EDIT!


#ifndef SENSOR_MESSAGE_RADIUS_MSGS_H
#define SENSOR_MESSAGE_RADIUS_MSGS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace sensor
{
template <class ContainerAllocator>
struct radius_msgs_
{
  typedef radius_msgs_<ContainerAllocator> Type;

  radius_msgs_()
    : stamp()
    , x(0.0)
    , y(0.0)
    , deg(0.0)  {
    }
  radius_msgs_(const ContainerAllocator& _alloc)
    : stamp()
    , x(0.0)
    , y(0.0)
    , deg(0.0)  {
  (void)_alloc;
    }



   typedef ros::Time _stamp_type;
  _stamp_type stamp;

   typedef double _x_type;
  _x_type x;

   typedef double _y_type;
  _y_type y;

   typedef double _deg_type;
  _deg_type deg;





  typedef boost::shared_ptr< ::sensor::radius_msgs_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::sensor::radius_msgs_<ContainerAllocator> const> ConstPtr;

}; // struct radius_msgs_

typedef ::sensor::radius_msgs_<std::allocator<void> > radius_msgs;

typedef boost::shared_ptr< ::sensor::radius_msgs > radius_msgsPtr;
typedef boost::shared_ptr< ::sensor::radius_msgs const> radius_msgsConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::sensor::radius_msgs_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::sensor::radius_msgs_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::sensor::radius_msgs_<ContainerAllocator1> & lhs, const ::sensor::radius_msgs_<ContainerAllocator2> & rhs)
{
  return lhs.stamp == rhs.stamp &&
    lhs.x == rhs.x &&
    lhs.y == rhs.y &&
    lhs.deg == rhs.deg;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::sensor::radius_msgs_<ContainerAllocator1> & lhs, const ::sensor::radius_msgs_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace sensor

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::sensor::radius_msgs_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::sensor::radius_msgs_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::sensor::radius_msgs_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::sensor::radius_msgs_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::sensor::radius_msgs_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::sensor::radius_msgs_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::sensor::radius_msgs_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c0b0ac57a0e348a96526a4b17c9b0e83";
  }

  static const char* value(const ::sensor::radius_msgs_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc0b0ac57a0e348a9ULL;
  static const uint64_t static_value2 = 0x6526a4b17c9b0e83ULL;
};

template<class ContainerAllocator>
struct DataType< ::sensor::radius_msgs_<ContainerAllocator> >
{
  static const char* value()
  {
    return "sensor/radius_msgs";
  }

  static const char* value(const ::sensor::radius_msgs_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::sensor::radius_msgs_<ContainerAllocator> >
{
  static const char* value()
  {
    return "time stamp\n"
"float64 x\n"
"float64 y \n"
"float64 deg\n"
;
  }

  static const char* value(const ::sensor::radius_msgs_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::sensor::radius_msgs_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.stamp);
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.deg);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct radius_msgs_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::sensor::radius_msgs_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::sensor::radius_msgs_<ContainerAllocator>& v)
  {
    s << indent << "stamp: ";
    Printer<ros::Time>::stream(s, indent + "  ", v.stamp);
    s << indent << "x: ";
    Printer<double>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<double>::stream(s, indent + "  ", v.y);
    s << indent << "deg: ";
    Printer<double>::stream(s, indent + "  ", v.deg);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SENSOR_MESSAGE_RADIUS_MSGS_H
