# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from sensor/gps_msgs.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import genpy

class gps_msgs(genpy.Message):
  _md5sum = "36f3f8d772df83d6901c751002087a5c"
  _type = "sensor/gps_msgs"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """time stamp
float64 longitude
float64 latitude
float64 altitude
float64 UTMx
float64 UTMy
float64 var_longitude
float64 var_latitude
float64 var_altitude
float64 var_UTMx
float64 var_UTMy
"""
  __slots__ = ['stamp','longitude','latitude','altitude','UTMx','UTMy','var_longitude','var_latitude','var_altitude','var_UTMx','var_UTMy']
  _slot_types = ['time','float64','float64','float64','float64','float64','float64','float64','float64','float64','float64']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       stamp,longitude,latitude,altitude,UTMx,UTMy,var_longitude,var_latitude,var_altitude,var_UTMx,var_UTMy

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(gps_msgs, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.stamp is None:
        self.stamp = genpy.Time()
      if self.longitude is None:
        self.longitude = 0.
      if self.latitude is None:
        self.latitude = 0.
      if self.altitude is None:
        self.altitude = 0.
      if self.UTMx is None:
        self.UTMx = 0.
      if self.UTMy is None:
        self.UTMy = 0.
      if self.var_longitude is None:
        self.var_longitude = 0.
      if self.var_latitude is None:
        self.var_latitude = 0.
      if self.var_altitude is None:
        self.var_altitude = 0.
      if self.var_UTMx is None:
        self.var_UTMx = 0.
      if self.var_UTMy is None:
        self.var_UTMy = 0.
    else:
      self.stamp = genpy.Time()
      self.longitude = 0.
      self.latitude = 0.
      self.altitude = 0.
      self.UTMx = 0.
      self.UTMy = 0.
      self.var_longitude = 0.
      self.var_latitude = 0.
      self.var_altitude = 0.
      self.var_UTMx = 0.
      self.var_UTMy = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_2I10d().pack(_x.stamp.secs, _x.stamp.nsecs, _x.longitude, _x.latitude, _x.altitude, _x.UTMx, _x.UTMy, _x.var_longitude, _x.var_latitude, _x.var_altitude, _x.var_UTMx, _x.var_UTMy))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.stamp is None:
        self.stamp = genpy.Time()
      end = 0
      _x = self
      start = end
      end += 88
      (_x.stamp.secs, _x.stamp.nsecs, _x.longitude, _x.latitude, _x.altitude, _x.UTMx, _x.UTMy, _x.var_longitude, _x.var_latitude, _x.var_altitude, _x.var_UTMx, _x.var_UTMy,) = _get_struct_2I10d().unpack(str[start:end])
      self.stamp.canon()
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_2I10d().pack(_x.stamp.secs, _x.stamp.nsecs, _x.longitude, _x.latitude, _x.altitude, _x.UTMx, _x.UTMy, _x.var_longitude, _x.var_latitude, _x.var_altitude, _x.var_UTMx, _x.var_UTMy))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.stamp is None:
        self.stamp = genpy.Time()
      end = 0
      _x = self
      start = end
      end += 88
      (_x.stamp.secs, _x.stamp.nsecs, _x.longitude, _x.latitude, _x.altitude, _x.UTMx, _x.UTMy, _x.var_longitude, _x.var_latitude, _x.var_altitude, _x.var_UTMx, _x.var_UTMy,) = _get_struct_2I10d().unpack(str[start:end])
      self.stamp.canon()
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_2I10d = None
def _get_struct_2I10d():
    global _struct_2I10d
    if _struct_2I10d is None:
        _struct_2I10d = struct.Struct("<2I10d")
    return _struct_2I10d
