# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from sensor/imu_msgs.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import genpy

class imu_msgs(genpy.Message):
  _md5sum = "5ebb085607169f8db0078a888ed031ff"
  _type = "sensor/imu_msgs"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """time stamp
float64 roll
float64 pitch 
float64 head
float64 var_roll
float64 var_pitch 
float64 var_head"""
  __slots__ = ['stamp','roll','pitch','head','var_roll','var_pitch','var_head']
  _slot_types = ['time','float64','float64','float64','float64','float64','float64']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       stamp,roll,pitch,head,var_roll,var_pitch,var_head

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(imu_msgs, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.stamp is None:
        self.stamp = genpy.Time()
      if self.roll is None:
        self.roll = 0.
      if self.pitch is None:
        self.pitch = 0.
      if self.head is None:
        self.head = 0.
      if self.var_roll is None:
        self.var_roll = 0.
      if self.var_pitch is None:
        self.var_pitch = 0.
      if self.var_head is None:
        self.var_head = 0.
    else:
      self.stamp = genpy.Time()
      self.roll = 0.
      self.pitch = 0.
      self.head = 0.
      self.var_roll = 0.
      self.var_pitch = 0.
      self.var_head = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_2I6d().pack(_x.stamp.secs, _x.stamp.nsecs, _x.roll, _x.pitch, _x.head, _x.var_roll, _x.var_pitch, _x.var_head))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.stamp is None:
        self.stamp = genpy.Time()
      end = 0
      _x = self
      start = end
      end += 56
      (_x.stamp.secs, _x.stamp.nsecs, _x.roll, _x.pitch, _x.head, _x.var_roll, _x.var_pitch, _x.var_head,) = _get_struct_2I6d().unpack(str[start:end])
      self.stamp.canon()
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_2I6d().pack(_x.stamp.secs, _x.stamp.nsecs, _x.roll, _x.pitch, _x.head, _x.var_roll, _x.var_pitch, _x.var_head))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.stamp is None:
        self.stamp = genpy.Time()
      end = 0
      _x = self
      start = end
      end += 56
      (_x.stamp.secs, _x.stamp.nsecs, _x.roll, _x.pitch, _x.head, _x.var_roll, _x.var_pitch, _x.var_head,) = _get_struct_2I6d().unpack(str[start:end])
      self.stamp.canon()
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_2I6d = None
def _get_struct_2I6d():
    global _struct_2I6d
    if _struct_2I6d is None:
        _struct_2I6d = struct.Struct("<2I6d")
    return _struct_2I6d
